# Generated by Django 3.2 on 2021-06-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=400)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(default='')),
            ],
        ),
    ]
